import Joi from 'joi';

export const validationSchema = Joi.object({
  APP_ID: Joi.string().uuid({ version: 'uuidv4' }).required(),
  NODE_ENV: Joi.string().required(),
  TESTING: Joi.bool().required(),
  PORT: Joi.number().required(),
  URL: Joi.string().required(),
  RABBITMQ_URL: Joi.string().required(),
  DATABASE_URL: Joi.string().required(),
  JWT_ACCESS_TIME: Joi.number().required(),
  JWT_CONFIRMATION_SECRET: Joi.string().required(),
  JWT_CONFIRMATION_TIME: Joi.number().required(),
  JWT_RESET_PASSWORD_SECRET: Joi.string().required(),
  JWT_RESET_PASSWORD_TIME: Joi.number().required(),
  JWT_REFRESH_SECRET: Joi.string().required(),
  JWT_REFRESH_TIME: Joi.number().required(),
  REFRESH_COOKIE: Joi.string().required(),
  COOKIE_SECRET: Joi.string().required(),
  EMAIL_HOST: Joi.string().required(),
  EMAIL_PORT: Joi.number().required(),
  EMAIL_SECURE: Joi.bool().required(),
  EMAIL_SERVICE: Joi.bool().required(),
  EMAIL_USER: Joi.string().email().required(),
  EMAIL_CLIENT_ID: Joi.string().required(),
  EMAIL_CLIEN_SECRET: Joi.string().required(),
  EMAIL_REDIRECT_URL: Joi.string().required(),
  EMAIL_REFRESH_TOKEN: Joi.string().required(),
  RABBITMQ_AUTH_QUEUE: Joi.string().required(),
  RABBITMQ_TOKEN_QUEUE: Joi.string().required(),
  RABBITMQ_MAILER_QUEUE: Joi.string().required(),
});
