version: "3.8"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      target: development
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - auth-service
      - user-service
      - booking-service
      - payment-service
      - mailer-service
      - postgres-db
      - mongo-db
    networks:
      - service-gateway
      - postgres-db
      - mongo-db

  auth-service:
    container_name: auth-microservice
    build:
      context: ./microservices/auth-service
      target: development
    ports:
      - 8001:8000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
      - mailer-service
    networks:
      - postgres-db
      - service-gateway

  user-service:
    container_name: user-microservice
    build:
      context: ./microservices/user-service
      target: development
    ports:
      - 8002:8000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
      - auth-service
    networks:
      - postgres-db
      - service-gateway

  booking-service:
    container_name: booking-microservice
    build:
      context: ./microservices/booking-service
      target: development
    ports:
      - 8003:8000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
      - auth-service
    networks:
      - mongo-db
      - service-gateway

  payment-service:
    container_name: payment-microservice
    build:
      context: ./microservices/payment-service
      target: development
    ports:
      - 8004:8000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
      - auth-service
    networks:
      - mongo-db
      - service-gateway

  mailer-service:
    container_name: mailer-microservice
    build:
      context: ./microservices/mailer-service
      target: development
    ports:
      - 8005:8000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - postgres-db
      - mongo-db

  postgres-db:
    image: "postgres:13.5"
    restart: "always"
    networks:
      - "postgres-db"
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "your password"

  mongo-db:
    image: mongo:4.2.0
    restart: always
    networks:
      - mongo-db
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

networks:
  service-gateway:
  postgres-db:
  mongo-db:

volumes:
  postgres:
  mongo_data:
