version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      args:
        - APP=api-gateway
    ports:
      - 9000:9000
    restart: on-failure
    depends_on:
      - auth-service
      - user-service
      - booking-service
      - payment-service
      - token-service
      - mailer-service
      - postgres-db
      - mongo-db
    networks:
      - service-gateway
      - postgres-db
      - mongo-db
  
  auth-service:
    container_name: auth-microservice
    build:
      context: .
      args:
        - APP=auth-service
    ports:
      - 9001:9000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - postgres-db
      - service-gateway

  user-service:
    container_name: user-microservice
    build:
      context: .
      args:
        - APP=user-service
    ports:
      - 9002:9000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - postgres-db
      - service-gateway

  booking-service:
    container_name: booking-microservice
    build:
      context: .
      args:
        - APP=booking-service
    ports:
      - 9003:9000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - mongo-db
      - service-gateway
  
  payment-service:
    container_name: payment-microservice
    build:
      context: .
      args:
        - APP=payment-service
    ports:
      - 9004:9000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - mongo-db
      - service-gateway

  token-service:
    container_name: token-microservice
    build:
      context: .
      args:
        - APP=token
    ports:
      - 9005:9000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - postgres-db
      - mongo-db

  mailer-service:
    container_name: mailer-microservice
    build:
      context: .
      args:
        - APP=mailer
    ports:
      - 9006:9000
    restart: on-failure
    depends_on:
      - postgres-db
      - mongo-db
    networks:
      - postgres-db
      - mongo-db

  postgres-db:
    image: "postgres:13.5"
    restart: "always"
    networks:
      - "postgres-db"
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "your password"

  mongo-db:
    image: mongo:4.2.0
    restart: always
    networks:
      - mongo-db
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

networks:
  service-gateway:
  postgres-db:
  mongo-db:

volumes:
  postgres:
  mongo_data: